---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - intern.malayparida2000
  resources:
  - systems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intern.malayparida2000
  resources:
  - systems/finalizers
  verbs:
  - update
- apiGroups:
  - intern.malayparida2000
  resources:
  - systems/status
  verbs:
  - get
  - patch
  - update
